export const MAINTENANCE_QUESTIONNAIRE_SECTIONS = [
  {
    id: "compilazione",
    title: "Informazioni sulla compilazione",
    eyebrow: "Per iniziare",
    description: "Indicate chi ha contribuito alle risposte e quali aree aziendali sono rappresentate.",
    questions: [
      { id: "meta.referente", label: "Referente principale" },
      { id: "meta.partecipanti", label: "Altri partecipanti alla compilazione" },
      { id: "meta.data", label: "Data di compilazione", type: "date" },
      { id: "meta.reparti", label: "Reparti o sedi rappresentati" },
    ],
  },
  {
    id: "obiettivi",
    title: "Obiettivi e problemi attuali",
    eyebrow: "01",
    description: "Partiamo dai problemi concreti che il nuovo strumento deve risolvere.",
    questions: [
      { id: "1.1", label: "Quali sono i principali problemi dell'attuale gestione delle manutenzioni?" },
      { id: "1.2", label: "Quali informazioni sono oggi più difficili o lente da trovare?" },
      { id: "1.3", label: "Quali attività o scadenze rischiano maggiormente di essere dimenticate?" },
      { id: "1.4", label: "Quali risultati deve garantire il nuovo strumento per essere considerato utile?" },
      { id: "1.5", label: "Quali sono le tre funzioni indispensabili per il primo rilascio?" },
    ],
  },
  {
    id: "perimetro",
    title: "Mezzi e attrezzature",
    eyebrow: "02",
    description: "Definiamo il perimetro e una categoria pilota realistica.",
    questions: [
      { id: "2.1", label: "Quali categorie devono essere gestite?", type: "multi", options: ["Carrelli elevatori", "Attrezzature", "Macchine operative", "Autovetture o furgoni aziendali", "Altri mezzi", "Altro"] },
      { id: "2.2", label: "Da quale categoria consigliate di partire come progetto pilota?" },
      { id: "2.3", label: "Quanti elementi sono presenti, approssimativamente, per ogni categoria?" },
      { id: "2.4", label: "Esistono elementi che non devono essere inclusi nel nuovo strumento?" },
      { id: "2.5", label: "Come viene identificato in modo univoco un mezzo o un'attrezzatura?", helper: "Per esempio: codice interno, matricola, targa o numero di serie." },
      { id: "2.6", label: "Esistono duplicati o elementi indicati con nomi o codici differenti nei vari documenti?" },
    ],
  },
  {
    id: "gestione-attuale",
    title: "Gestione attuale",
    eyebrow: "03",
    description: "Raccontate il processo reale, compresi i passaggi svolti fuori dai sistemi ufficiali.",
    questions: [
      { id: "3.1", label: "Quali strumenti utilizzate oggi?", type: "multi", options: ["Cartelle di rete", "SharePoint", "File Excel", "File Word", "PDF", "Email", "Documenti cartacei", "Software del fornitore", "Altro"] },
      { id: "3.2", label: "Dove sono conservate le anagrafiche dei mezzi e delle attrezzature?" },
      { id: "3.3", label: "Dove sono registrate le manutenzioni effettuate?" },
      { id: "3.4", label: "Dove sono registrate e controllate le scadenze?" },
      { id: "3.5", label: "Chi aggiorna attualmente queste informazioni?" },
      { id: "3.6", label: "Descrivete i passaggi effettuati oggi per ricostruire la situazione completa di un mezzo." },
      { id: "3.7", label: "Quali informazioni vengono scambiate soltanto tramite telefono, email o comunicazioni verbali?" },
    ],
  },
  {
    id: "anagrafica",
    title: "Scheda anagrafica",
    eyebrow: "04",
    description: "Individuiamo i dati comuni e quelli specifici di ogni categoria.",
    questions: [
      { id: "4.1", label: "Quali dati devono essere presenti per tutti i mezzi e quali devono essere obbligatori?", helper: "Considerate codice interno, categoria, marca, modello, matricola, targa, seriale, anno, sede, reparto, responsabile, stato e note." },
      { id: "4.2", label: "Quali dati servono soltanto per alcune categorie?", helper: "Per esempio: portata, alimentazione, telaio, chilometri, ore motore o ubicazione precisa." },
      { id: "4.3", label: "Quali stati deve poter assumere un bene?", type: "multi", options: ["Attivo", "In manutenzione", "Fuori servizio", "Dismesso", "Altro"] },
      { id: "4.4", label: "Chi può cambiare lo stato di un bene?" },
      { id: "4.5", label: "Un bene può cambiare sede, reparto o responsabile?" },
      { id: "4.6", label: "I trasferimenti e i cambi di responsabile devono rimanere nello storico?" },
      { id: "4.7", label: "Serve registrare letture periodiche come chilometri oppure ore di funzionamento?" },
      { id: "4.8", label: "Serve applicare un QR code o un'etichetta per aprire rapidamente la scheda?" },
    ],
  },
  {
    id: "ordinarie",
    title: "Manutenzioni ordinarie",
    eyebrow: "05",
    description: "Descrivete gli interventi programmati e come viene determinata la periodicità.",
    questions: [
      { id: "5.1", label: "Quali tipi di manutenzione ordinaria vengono eseguiti?" },
      { id: "5.2", label: "Come viene stabilito quando eseguire una manutenzione ordinaria?", type: "multi", options: ["Data o intervallo temporale", "Chilometri", "Ore di funzionamento", "Controllo manuale", "Indicazione del fornitore", "Altro"] },
      { id: "5.3", label: "Esistono piani differenti per categoria, marca o modello?" },
      { id: "5.4", label: "Chi programma una manutenzione ordinaria?" },
      { id: "5.5", label: "Quali informazioni devono essere registrate obbligatoriamente alla conclusione?" },
      { id: "5.6", label: "Come viene stabilita la manutenzione successiva?" },
      { id: "5.7", label: "La prossima scadenza decorre dalla data prevista o dalla data effettiva dell'intervento?" },
    ],
  },
  {
    id: "straordinarie",
    title: "Guasti e manutenzioni straordinarie",
    eyebrow: "06",
    description: "Ricostruiamo il flusso dalla prima segnalazione alla rimessa in servizio.",
    questions: [
      { id: "6.1", label: "Come viene segnalato oggi un guasto o un'anomalia?" },
      { id: "6.2", label: "Chi deve poter aprire una segnalazione?" },
      { id: "6.3", label: "Quali informazioni minime deve contenere una segnalazione?" },
      { id: "6.4", label: "È necessario indicare una gravità o una priorità?" },
      { id: "6.5", label: "Chi decide se il mezzo può continuare a essere utilizzato?" },
      { id: "6.6", label: "In quali casi il mezzo deve essere indicato come fuori servizio?" },
      { id: "6.7", label: "Chi assegna l'intervento a un manutentore interno o a un fornitore?" },
      { id: "6.8", label: "È necessaria una verifica o un'approvazione prima di chiudere l'intervento?" },
      { id: "6.9", label: "Un intervento chiuso può essere riaperto o modificato? Da chi?" },
    ],
  },
  {
    id: "ciclo",
    title: "Ciclo di un intervento",
    eyebrow: "07",
    description: "Definiamo stati, responsabilità e condizioni di chiusura.",
    questions: [
      { id: "7.1", label: "Descrivete tutti i passaggi, dalla segnalazione alla conclusione dell'intervento." },
      { id: "7.2", label: "Quali stati sono necessari?", type: "multi", options: ["Segnalato", "Pianificato", "In corso", "Sospeso", "Completato", "Annullato", "Altro"] },
      { id: "7.3", label: "Chi può effettuare ciascun passaggio o cambio di stato?" },
      { id: "7.4", label: "Quali dati devono essere obbligatori per poter chiudere un intervento?" },
      { id: "7.5", label: "Devono essere registrate sia la data prevista sia la data effettiva?" },
      { id: "7.6", label: "Deve essere registrato il periodo durante il quale il bene è rimasto fermo?" },
      { id: "7.7", label: "Una manutenzione può interessare più mezzi o attrezzature contemporaneamente?" },
    ],
  },
  {
    id: "costi",
    title: "Fornitori, costi e ricambi",
    eyebrow: "08",
    description: "Chiarite il livello di dettaglio economico necessario nel lavoro quotidiano.",
    questions: [
      { id: "8.1", label: "Gli interventi vengono eseguiti da personale interno, fornitori esterni o entrambi?" },
      { id: "8.2", label: "Serve un elenco strutturato e riutilizzabile dei fornitori?" },
      { id: "8.3", label: "Quali dati del fornitore devono essere disponibili?" },
      { id: "8.4", label: "Quali costi devono essere registrati?", type: "multi", options: ["Costo complessivo", "Manodopera", "Ricambi", "Trasporto o uscita", "Preventivo", "Consuntivo", "Altro"] },
      { id: "8.5", label: "Chi può consultare i costi?" },
      { id: "8.6", label: "Servono riferimenti a ordine, preventivo, fattura o centro di costo?" },
      { id: "8.7", label: "I ricambi devono essere soltanto descritti oppure gestiti come un vero magazzino?" },
    ],
  },
  {
    id: "scadenze",
    title: "Scadenze",
    eyebrow: "09",
    description: "Individuiamo periodicità, responsabilità, soglie e casi bloccanti.",
    questions: [
      { id: "9.1", label: "Quali tipi di scadenza devono essere gestiti?" },
      { id: "9.2", label: "Quali scadenze sono obbligatorie per legge o per regole aziendali?" },
      { id: "9.3", label: "Quali scadenze impediscono l'utilizzo del bene quando sono superate?" },
      { id: "9.4", label: "Come devono essere definiti gli stati regolare, in scadenza, urgente e scaduta?" },
      { id: "9.5", label: "Con quanto anticipo devono essere segnalate?", type: "multi", options: ["90 giorni", "60 giorni", "30 giorni", "15 giorni", "7 giorni", "Altro"] },
      { id: "9.6", label: "Le soglie devono essere uguali per tutte le scadenze o configurabili per tipo?" },
      { id: "9.7", label: "Chi è responsabile della gestione di ciascuna scadenza?" },
      { id: "9.8", label: "È possibile posticipare una scadenza? Chi può autorizzarlo?" },
      { id: "9.9", label: "In caso di posticipo deve essere obbligatoria una motivazione?" },
      { id: "9.10", label: "Dopo il completamento, la scadenza successiva deve essere generata automaticamente?" },
    ],
  },
  {
    id: "notifiche",
    title: "Avvisi e notifiche",
    eyebrow: "10",
    description: "Definiamo destinatari, canali ed eventuali escalation.",
    questions: [
      { id: "10.1", label: "Chi deve essere avvisato per una scadenza imminente?" },
      { id: "10.2", label: "Il destinatario dipende dal bene, dalla sede, dal reparto o dal tipo di scadenza?" },
      { id: "10.3", label: "Quali canali devono essere utilizzati?", type: "multi", options: ["Dashboard del modulo", "Campanella T-Hub", "Email individuale", "Riepilogo giornaliero", "Riepilogo settimanale", "Altro"] },
      { id: "10.4", label: "Gli avvisi devono essere ripetuti? Con quale frequenza?" },
      { id: "10.5", label: "Serve un'escalation quando la scadenza viene superata? Verso chi?" },
      { id: "10.6", label: "Quando deve scomparire una notifica?" },
    ],
  },
  {
    id: "documenti",
    title: "Documenti",
    eyebrow: "11",
    description: "Descrivete documenti, vincoli, visibilità e regole di conservazione.",
    questions: [
      { id: "11.1", label: "Quali documenti devono essere associati direttamente al mezzo o all'attrezzatura?" },
      { id: "11.2", label: "Quali documenti devono essere associati a uno specifico intervento?" },
      { id: "11.3", label: "Quali documenti sono obbligatori per chiudere un intervento?" },
      { id: "11.4", label: "Quali formati vengono utilizzati?", type: "multi", options: ["PDF", "Word", "Excel", "Immagini", "Altro"] },
      { id: "11.5", label: "Qual è la dimensione massima indicativa dei documenti?" },
      { id: "11.6", label: "Un documento può essere sostituito o eliminato? Da chi?" },
      { id: "11.7", label: "Devono essere conservate anche le versioni precedenti?" },
      { id: "11.8", label: "Un documento può avere una propria data di scadenza?" },
      { id: "11.9", label: "Esistono documenti che non devono essere visibili a tutti gli utenti del modulo?" },
      { id: "11.10", label: "Come sono organizzate oggi le cartelle e come vengono nominati i file?" },
    ],
  },
  {
    id: "storico",
    title: "Storico",
    eyebrow: "12",
    description: "Stabiliamo quali eventi conservare e quanto storico recuperare.",
    questions: [
      { id: "12.1", label: "Quali eventi devono comparire nello storico completo?", type: "multi", options: ["Manutenzioni ordinarie", "Manutenzioni straordinarie", "Guasti e anomalie", "Verifiche", "Scadenze", "Documenti", "Periodi di fermo", "Cambi sede o reparto", "Cambi responsabile", "Cambi stato", "Altro"] },
      { id: "12.2", label: "Deve essere sempre visibile chi ha inserito o modificato un'informazione?" },
      { id: "12.3", label: "Quali informazioni non devono mai poter essere cancellate?" },
      { id: "12.4", label: "Quanto storico esistente deve essere importato?" },
      { id: "12.5", label: "È accettabile importare vecchi interventi con informazioni incomplete?" },
      { id: "12.6", label: "Chi controllerà e correggerà i dati importati?" },
    ],
  },
  {
    id: "report",
    title: "Ricerca, dashboard e report",
    eyebrow: "13",
    description: "Indicate ciò che deve essere trovato o capito rapidamente.",
    questions: [
      { id: "13.1", label: "Con quali dati cercate normalmente un mezzo?", type: "multi", options: ["Codice interno", "Matricola", "Targa", "Numero di serie", "Marca", "Modello", "Categoria", "Sede", "Reparto", "Responsabile", "Altro"] },
      { id: "13.2", label: "Quali filtri devono essere immediatamente disponibili?" },
      { id: "13.3", label: "Quali numeri o situazioni devono comparire nella dashboard iniziale?" },
      { id: "13.4", label: "Quali situazioni devono essere evidenziate come urgenti?" },
      { id: "13.5", label: "Quali report preparate periodicamente oggi?" },
      { id: "13.6", label: "Servono esportazioni in Excel o PDF? Quali?" },
      { id: "13.7", label: "A chi vengono inviati i report e con quale frequenza?" },
    ],
  },
  {
    id: "autorizzazioni",
    title: "Utenti e autorizzazioni",
    eyebrow: "14",
    description: "Assegniamo responsabilità precise alle diverse operazioni.",
    questions: [
      { id: "14.1", label: "Quali gruppi di persone devono poter consultare il modulo?" },
      { id: "14.2", label: "Chi deve poter creare o modificare l'anagrafica dei beni?" },
      { id: "14.3", label: "Chi deve poter aprire, modificare e chiudere gli interventi?" },
      { id: "14.4", label: "Chi deve poter creare, modificare o posticipare le scadenze?" },
      { id: "14.5", label: "Chi deve poter caricare, sostituire o eliminare documenti?" },
      { id: "14.6", label: "Chi deve poter consultare costi, preventivi e fatture?" },
      { id: "14.7", label: "Gli utenti devono vedere tutto oppure soltanto la propria sede o reparto?" },
      { id: "14.8", label: "Chi sarà l'amministratore funzionale del modulo?" },
    ],
  },
];

export const MAINTENANCE_QUESTIONS = MAINTENANCE_QUESTIONNAIRE_SECTIONS.flatMap((section) => section.questions);

export function isMaintenanceAnswerComplete(value) {
  if (Array.isArray(value)) return value.length > 0;
  return typeof value === "string" && value.trim().length > 0;
}

export function maintenanceQuestionnaireProgress(answers = {}) {
  const completed = MAINTENANCE_QUESTIONS.filter((question) => isMaintenanceAnswerComplete(answers[question.id])).length;
  const total = MAINTENANCE_QUESTIONS.length;
  return { completed, total, percent: total ? Math.round((completed / total) * 100) : 0 };
}
